### ISSUE TITLE
n_bootstraps for MovingBootstrap doesn't work (n is still 10).

### ISSUE THREAD

**Issue by oldrichsmejkal** [astrogilda/tsbootstrap#157]
**Describe the bug**

n_bootstraps for MovingBootstrap doesn't work (n is still 10).

Seems like just adding n_bootstrap to MovingBlockBootstrapConfig like below solves the problem:
        self.config = MovingBlockBootstrapConfig(
            n_bootstraps = n_bootstraps,
...

(tsbootstrap/block_bootstrap.py: 402)

**Comment by benHeid** [comment]
I think it is fixed on main. See #154

@astrogilda would it make sense to make a minor release with the bugfix?

**Comment by astrogilda** [comment]
@benHeid I think you are absolutely right. I'll aim for this weekend, with this plus a couple of other fixes that @fkiraly has suggested about a month or so ago.
@oldrichsmejkal give me a few days :)

**Comment by astrogilda** [comment]
@oldrichsmejkal this is now fixed with 0.1.2. closing the issue.
