### ISSUE TITLE
Make compatible with 3.12

### ISSUE THREAD

**Issue by astrogilda** [astrogilda/tsbootstrap#38]
- tsbootstrap version: 0.0.3

Follows issue #12

**Comment by fkiraly** [comment]
probably should be 0.1.0, no?

**Comment by astrogilda** [comment]
> probably should be 0.1.0, no?

Nah the current version is 0.0.3; after we fix everything and this is ready to be adapter-ed into sktime we'll change it to 0.1.0

**Comment by fkiraly** [comment]
I see, makes sense.

**Comment by fkiraly** [comment]
done in #57
