### ISSUE TITLE
Sphinx documentation does not render

### ISSUE THREAD

**Issue by astrogilda** [astrogilda/tsbootstrap#7]
- tsbootstrap version: 0.0.3
- Python version: 3.10
- Operating System: Ubuntu 20

### Expected behavior

Sphinx documentation to be built properly and rendered on github

### Actual behavior

However, it renders correctly on my local system but not online

### Code to reproduce the problem

```
cd docs
poetry run make html
```
Then open `docs/build/html/index.html` in a web browser to view your generated documentation.

**Comment by fkiraly** [comment]
@astrogilda, why are we not getting a readthedocs build off PR?
Have you activated the integration?

**Comment by astrogilda** [comment]
> [@astrogilda](https://github.com/astrogilda), why are we not getting a readthedocs build off PR? Have you activated the integration?

Yep! pushed this just now. opening a pr.
