### ISSUE TITLE
stationary bootstrap fails tests sporadically

### ISSUE THREAD

**Issue by astrogilda** [astrogilda/tsbootstrap#82]
due to misalignment between sampled_block_length and min_block_length.

**Comment by fkiraly** [comment]
duplicate of #73?

**Comment by astrogilda** [comment]
> duplicate of #73?

ah yes! this issue has a branch and a pr associated with it. how do I break those connections and reconnect them with #73 so i can delete this one?

**Comment by fkiraly** [comment]
via click on this:
![image](https://github.com/astrogilda/tsbootstrap/assets/7985502/4ad68281-eb9d-49d6-9076-4edf408ffecd)
(right panel)

You could also connect the PR to both, issues automatically get closed when a connected PR is merged.

Also, btw, it's not your fault - it was originally named after `BaseBlockBootstrap`, but later I narrowed it down to `StationaryBlockBootstrap` and renamed the issue.
