### ISSUE TITLE
Add skbase suite tests and ensure current bootstrap classes pass

### ISSUE THREAD

**Issue by astrogilda** [astrogilda/tsbootstrap#9]
Update by @fkiraly:

The task tracked by this issue is to:

* ensure all bootstrap estimators in `tsbootstrap` are run through the standard `skbase` test suite for objects and estimators
* ensure all bootstrap estimators in `tsbootstrap` pass those tests, including possibly changes and general learnings related to API or internals.

---

- tsbootstrap version: 0.0.3
- Python version: 3.10 and 3.11
- Operating System: Linux and OS

TODO: Add stringent API tests to allow for reliable and robust integration with `sktime`

**Comment by fkiraly** [comment]
happy to help with this, as discussed - I assume the best time is once #8 is done.

**Comment by astrogilda** [comment]
Yeah I agree

**Comment by fkiraly** [comment]
As discussion on Feb 5:

* @astrogilda will make a PR with a few bootstrap `__init__` APIs changed
* @fkiraly will use this to make changes towards `skbase` compatibility and report on findings (e.g., any gaps)

**Comment by fkiraly** [comment]
as discussed with @astrogilda on Feb 9, we are going to loosen the contract for now to admit `kwargs` - I will try by catching that specific exception, othewise running test for the parent.
